### ISSUE TITLE
computer smoking

### ISSUE THREAD

**Issue by kjeghueirgh** [GoobyCorp/FSPD-Plus-Plus#1]
Hello I ran your code and now dn are on fire, any tips?

**Comment by GoobyCorp** [comment]
Sorry about that, it's probably my multi-threaded optimizations.

**Comment by kjeghueirgh** [comment]
i rewrote the threading in brainfuck, all good now. Thanks!

**Comment by GoobyCorp** [comment]
Try running now, my sockets might be too powerful for your PC.

**Comment by kjeghueirgh** [comment]
hot 🔥🥵🔥🔥 fire ahh
